services:
  safenav-core:
    build: ./core
    ports:
      - "8000:8000"
    # Desarrollo, evita tener que reconstruir la imagen para ver cambios
    # TODO: Eliminar en producción
    volumes:
      - ./core:/app
    command: >
      uvicorn api.routes_controller:app
      --host 0.0.0.0
      --port 8000
      --reload
