@startuml

!include docs/uml/theme.puml
skinparam linetype ortho
skinparam defaultTextAlignment center
skinparam shadowing false
skinparam ArrowFontSize 10
skinparam ComponentFontSize 12
skinparam PackageFontSize 11
skinparam PackagePadding 25
skinparam nodesep 80
skinparam ranksep 100

' === User Interface (vertical layout) ===
component "User Interface System" <<system>> as UISys {
  top to bottom direction
  component "User Interface\n(Web / Mobile / CLI)" as UI
}

' === SafeNav Core (horizontal layout) ===
component "SafeNav Core" <<system>> as Core {
  component "API Layer (HTTP Controller)" as API
  component "Routing Engine\n(RE)" as RE
  component "Context Analyzer\n(CA)" as CA
  component "                                Data Management (DM)                               " as DM

  ' === Internal Interfaces ===
  API -down-> RE :    Route request
  RE .up.> API :      Route results
  API -down-> CA :    Route candidates
  API -down-> DM :    Map view request
  DM .up.> API :      Map view response
  CA .up.> API :      Route + scores
  CA -down-> DM :     Context data request
  DM .up.> CA :       Context data response
  RE -down-> DM :     Graph data request
  DM .up.> RE :       Graph data response
}

' === Connection between UI and Core ===
UI --> API : HTTP request\n(Map view request)
API ..> UI : HTTP response\n(Map view)
UI --> API : HTTP request\n(Route request)
API ..> UI : HTTP response\n(Route results and alerts)

' === External Data Sources (vertical layout) ===
package "External Data Sources" {
  top to bottom direction
  component "Map Services\n(MapAPI)"         <<external>> as MapAPI
  component "Meteo Sources\n(MeteoAPI)"      <<external>> as Meteo
  component "Local Open Data\n(OpenDataAPI)" <<external>> as OpenData
}

' === External Interfaces ===
DM --> MapAPI : Map data requests
MapAPI ..> DM : Map data responses
DM --> Meteo : Weather data requests
Meteo ..> DM : Weather data responses
DM --> OpenData : Urban open data requests
OpenData ..> DM : Urban data responses


@enduml
