@startuml
note across
Scenario 0 – Default Map Visualization
"This scenario illustrates the initial map visualization displayed
when the application is loaded, before the user selects an origin
or destination.\n
The interface is implemented through the Leaflet library,
which fetches map data from the MapAPI (Open Street Map) to render the default city map.
This scenario does not involve route calculation or context analysis, as it focuses solely 
on displaying the map view to the user upon launching the application."
end note

actor "User" as User
participant "User Interface" as UI
participant "Map Services" as MapAPI

User -> UI : Open application

UI -> MapAPI : I_Map_Data_Access: fetchMapData(default area)\n(through Leaflet)
MapAPI --> UI : I_Map_Data_Access: MapData

UI -> UI : Display default city map
@enduml
